# Site
name: 'Brad Leege'
description: 'Personal Web site of Brad Leege'
baseurl: ''
domain_name: 'www.leege.io'
permalink: /:year/:month/:day/:title.html
google_analytics: 'G-B5PX8DLP81'
include: ["_pages"]

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/

# SEO
title: 'Brad Leege'
url: 'www.leege.io'
author: 'Brad Leege'
twitter:
  username: bradleege
  card: summary
social:
  name: Brad Leege
  links:
    - https://twitter.com/bradleege
    - https://www.linkedin.com/in/bradleege
    - https://github.com/bleege
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
