name: Brad Leege
#description: Personal Web site of Brad Leege.
meta_description: Personal Web site of Brad Leege.

markdown: kramdown
highlighter: rouge
logo: false
baseurl: /
domain_name: 'www.leege.io'
google_analytics: 'UA-100713791-1'
plugins_dir: 
- jekyll-paginate
- jekyll-seo-tag

# Paginate
paginate: 5
paginate_path: "/blog/page-:num/"

# Details for the RSS feed generator
url:            'http://www.leege.io'
author:         'Brad Leege'

# SEO
twitter:
  username: bradleege
social:
  name: Brad Leege
  links:
      - https://twitter.com/bradleege
      - https://www.linkedin.com/in/bradleege
      - https://github.com/bleege
