name: Brad Leege
# description: 
meta_description: "Brad Leege Meta"

markdown: kramdown
highlighter: pygments
logo: false
paginate: 15
baseurl: /
domain_name: 'www.leege.io'
google_analytics: 'UA-100713791-1'
gems: [jekyll-paginate]

# Details for the RSS feed generator
url:            'http://www.leege.io'
author:         'Brad Leege'
